### ISSUE TITLE
CSS Order - Custom CSS goes last.

### ISSUE THREAD

**Issue by kststudio** [Jtrinity87/personalProject#1]
https://github.com/Jtrinity87/personalProject/blob/e482abbe48d9b6ac903d044255b4a24cba9fd9a4/homePage.html#L7

When you are using a 3rd party CSS or JS, you want your custom code to mention last in the order of CSS links or JS scripts. So in this case, move this line to be on LINE 8 instead.

**Comment by Jtrinity87** [comment]
Moved css link from line 7 to line 8"

**Comment by Jtrinity87** [comment]
Should I have put "<link rel="stylesheet" href="style.css">" at the end of the link?

**Comment by kststudio** [comment]
which link?
