### ISSUE TITLE
Remove any commented code

### ISSUE THREAD

**Issue by kststudio** [Jtrinity87/personalProject#4]
https://github.com/Jtrinity87/personalProject/blob/e482abbe48d9b6ac903d044255b4a24cba9fd9a4/homePage.html#L23

Double-check your work for any code that has been commented out. You should remove these because you are not actively using them in order for the page to load. Keeping commented code can be confusing for others to understand why it was commented out in the first place. Comments with real comments are okay.

**Comment by Jtrinity87** [comment]
Took out all unnecessary commented out text from all pages including css.
